# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
# Create app directory
WORKDIR /app

RUN npm install -g lerna cross-env rimraf ts-eager --loglevel notice

# to make use of caching, copy only package files and install dependencies
COPY package.json .
COPY packages/client/package.json ./packages/client/
COPY packages/client-core/package.json ./packages/client-core/
COPY packages/common/package.json ./packages/common/
COPY packages/contracts/package.json ./packages/contracts/
COPY packages/ops/package.json ./packages/ops/
COPY packages/rinkeby/package.json ./packages/rinkeby/
COPY packages/server/package.json ./packages/server/
COPY packages/server-core/package.json ./packages/server-core/
COPY packages/social/package.json ./packages/social/
COPY packages/simulator/package.json ./packages/simulator/

RUN npm install --production=false --loglevel notice --legacy-peer-deps

COPY . .

RUN rm .dockerignore

# copy then compile the code

ENV APP_ENV=production

CMD ["scripts/run-builder.sh"]
