version: '2.3'
services:
  db:
    image: mariadb:10.6
    container_name: creator_db
    environment:
      MYSQL_ROOT_PASSWORD: creator-root-pa$$w0rd
      MYSQL_DATABASE: creator
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
  redis:
    image: redis
    container_name: creator_redis
    command: redis-server
    ports:
      - '6379:6379'
